### ISSUE TITLE
这个库的作用是啥

### ISSUE THREAD

**Issue by otakustay** [ecomfe/babel-plugin-transform-modules-amd#1]
和[babel-plugin-transform-modules-amd](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-amd)的区别有哪些，我们应该在什么场景下使用？

**Comment by liuxuanzy** [comment]
写这个东西的原因主要是babel官方提供的那个类库太暴力了，不完全统计在开发的时候使用了：
1. getter/setter：IE9+支持并且无法shim，也没有loose模式
2. 所有模块使用__esmodule进行标识，如果我开发的是一个类库，并且我的使用者不使用es2015，那么他要经常写这样的代码 var foo = require('foo')['default']; 而大部分情况下，我们习惯的是var foo = require('foo');
3. 所有的helper使用的都是Object.defineProperty，必须依赖ES5.shim
4. 与es3的相关插件冲突，导出的代码一定会写成exports.default，而不是exports['default']

官方版本是基于commonjs规范打包的，翻译出来的代码体积会比较大，'interopRequireWildcard' 和 ‘interopRequireDefault’ 两个helper因为babel本身要用到，所以没办法使用runtime。

最后AMD提倡的是引用前置，ES2015规范的引用就近。

------------------ 原始邮件 ------------------
发件人: "Gray Zhang";notifications@github.com;
发送时间: 2016年2月26日(星期五) 下午2:20
收件人: "ecomfe/babel-plugin-transform-modules-amd"babel-plugin-transform-modules-amd@noreply.github.com; 

主题: [babel-plugin-transform-modules-amd] 这个库的作用是啥 (#1)

和babel-plugin-transform-modules-amd的区别有哪些，我们应该在什么场景下使用？

**Comment by otakustay** [comment]
GOOD~
